name: Promote to live
on: 
  workflow_dispatch:
    inputs:
      track:
        description: 'Track'     
        required: true
        default: 'stg'

jobs:
  promote:
    name: Promote staging version to live
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Generate dalamud-distrib version file
      shell: powershell
      env:
        DALAMUD_TRACK: ${{ github.event.inputs.track }}
      run: |
        $trackName = $env:DALAMUD_TRACK
        Expand-Archive -Path ".\${trackName}\latest.zip" -DestinationPath .\scratch
        
        $dllBytes = [System.IO.File]::ReadAllBytes("$(Get-Location)\scratch\Dalamud.dll")
        $assembly = [System.Reflection.Assembly]::Load($dllBytes)
        $newVersion = $assembly.GetName().Version.ToString()
        Remove-Item -Force -Recurse .\scratch

        $versionData = Get-Content .\version | ConvertFrom-Json
        $oldVersion = $versionData.AssemblyVersion
        if ($oldVersion -eq $newVersion) {
          Write-Host "Nothing to promote"
        } else {
          Copy-Item -Force -Path ".\${trackName}\latest.zip" -Destination .\latest.zip
          $versionData.AssemblyVersion = $newVersion
          [System.IO.File]::WriteAllLines(".\version", $versionData | ConvertTo-Json -Compress)
          
          Write-Host "Promotion OK"
        }
        
        echo "DVER=${newVersion}" >> $Env:GITHUB_ENV
        
    - name: Commit changes
      shell: bash
      run: |
        git config --global user.name "Actions User"
        git config --global user.email "actions@github.com"
        
        git add .
        git commit -m "[CI] Promoting for ${DVER} from ${{ github.event.inputs.track }}" || true
        
        git push origin main || true
